# Generated by Django 3.1.2 on 2021-07-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('cantidad', models.CharField(max_length=100)),
            ],
        ),
    ]
